# Generated by Django 4.0.1 on 2022-02-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='photos/pattern.jpg', null=True, upload_to='photos'),
        ),
    ]
